---
- name: 'Creating users for FILE server'
  hosts: file

  tasks:
    - name: 'Add users'

      user:
        system: true
        state: present
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        createhome: "{{ item.createhome }}"
        home: "{{ item.home }}"
        skeleton: "{{ item.skeleton }}"
      
      with_items:
        - { name: 'house', groups: 'wheel', shell: '/bin/bash', createhome: 'yes', home: '/home/house', skeleton: '/etc/skel' }
        - { name: 'chase', groups: 'wheel', shell: '/bin/bash', createhome: 'yes', home: '/home/chase', skeleton: '/etc/skel' }
    
    - name: 'Read passwd file...'
      shell:
        cmd: cat /etc/passwd | tail -5
      register: results
      changed_when: results.rc == 0
    
    - name: 'Printing last 5 users from passwd... '
      debug:
        var: results.stdout_lines
...